// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// This file is generated by scripts/generate-config.js
// Run 'npm run generate-config' to regenerate

import { UptimeData, ResponseTimeData, ServiceStatus } from './types';

// Location definitions
export interface Location {
  name: string;
  code: string;
  coordinates: [number, number];
  region: string;
}

export const LOCATIONS: Location[] = [
  {
    "name": "Los Angeles",
    "code": "la",
    "coordinates": [
      -118.2437,
      34.0522
    ],
    "region": "North America"
  },
  {
    "name": "New York",
    "code": "ny",
    "coordinates": [
      -74.006,
      40.7128
    ],
    "region": "North America"
  },
  {
    "name": "London",
    "code": "ldn",
    "coordinates": [
      -0.1276,
      51.5074
    ],
    "region": "Europe"
  },
  {
    "name": "Singapore",
    "code": "sg",
    "coordinates": [
      103.8198,
      1.3521
    ],
    "region": "Asia-Pacific"
  },
  {
    "name": "São Paulo",
    "code": "sp",
    "coordinates": [
      -46.6333,
      -23.5505
    ],
    "region": "South America"
  }
];

// Service definitions
interface ServiceConfig {
  id: string;
  name: string;
  url: string;
  statusUrl: string;
}

export const SERVICES: ServiceConfig[] = [
  {
    "id": "Zapier",
    "name": "Zapier",
    "url": "https://status.zapier.com/api/v2/status.json",
    "statusUrl": "https://status.zapier.com"
  },
  {
    "id": "Salesforce",
    "name": "Salesforce",
    "url": "https://api.status.salesforce.com/v1/instances/status",
    "statusUrl": "https://status.salesforce.com"
  },
  {
    "id": "Google Cloud",
    "name": "Google Cloud",
    "url": "https://status.cloud.google.com/summary.json",
    "statusUrl": "https://status.cloud.google.com"
  },
  {
    "id": "Microsoft Azure",
    "name": "Microsoft Azure",
    "url": "https://azure.status.microsoft.com/en-us/status/feed/",
    "statusUrl": "https://azure.status.microsoft.com/en-us/status"
  },
  {
    "id": "CallRail",
    "name": "CallRail",
    "url": "https://status.callrail.com/api/v2/status.json",
    "statusUrl": "https://status.callrail.com"
  },
  {
    "id": "WordPress Site",
    "name": "WordPress Site",
    "url": "https://hratchyan.com",
    "statusUrl": "https://hratchyan.com"
  }
];

// Service directory mapping (for Upptime-generated directories)
const SERVICE_DIR_MAP: Record<string, string> = {
  'Zapier (Los Angeles)': 'zapier-la',
  'Zapier (New York)': 'zapier-ny',
  'Zapier (London)': 'zapier-ldn',
  'Zapier (Singapore)': 'zapier-sg',
  'Zapier (São Paulo)': 'zapier-sp',
  'Salesforce (Los Angeles)': 'salesforce-la',
  'Salesforce (New York)': 'salesforce-ny',
  'Salesforce (London)': 'salesforce-ldn',
  'Salesforce (Singapore)': 'salesforce-sg',
  'Salesforce (São Paulo)': 'salesforce-sp',
  'Google Cloud (Los Angeles)': 'google-cloud-la',
  'Google Cloud (New York)': 'google-cloud-ny',
  'Google Cloud (London)': 'google-cloud-ldn',
  'Google Cloud (Singapore)': 'google-cloud-sg',
  'Google Cloud (São Paulo)': 'google-cloud-sp',
  'Microsoft Azure (Los Angeles)': 'microsoft-azure-la',
  'Microsoft Azure (New York)': 'microsoft-azure-ny',
  'Microsoft Azure (London)': 'microsoft-azure-ldn',
  'Microsoft Azure (Singapore)': 'microsoft-azure-sg',
  'Microsoft Azure (São Paulo)': 'microsoft-azure-sp',
  'CallRail (Los Angeles)': 'callrail-la',
  'CallRail (New York)': 'callrail-ny',
  'CallRail (London)': 'callrail-ldn',
  'CallRail (Singapore)': 'callrail-sg',
  'CallRail (São Paulo)': 'callrail-sp',
  'WordPress Site (Los Angeles)': 'wordpress-site-la',
  'WordPress Site (New York)': 'wordpress-site-ny',
  'WordPress Site (London)': 'wordpress-site-ldn',
  'WordPress Site (Singapore)': 'wordpress-site-sg',
  'WordPress Site (São Paulo)': 'wordpress-site-sp'
};

export async function getServiceStatus(serviceId: string, locationCode?: string): Promise<ServiceStatus> {
  const service = SERVICES.find(s => s.id === serviceId);
  const location = locationCode ? LOCATIONS.find(l => l.code === locationCode) : undefined;
  
  // Return error state if service not found in config
  if (!service) {
    return {
      name: serviceId,
      url: '',
      statusUrl: '',
      status: 'unknown',
      uptime: '0%',
      responseTime: 0,
      lastChecked: new Date().toISOString(),
      error: 'Service configuration not found',
    };
  }

  try {
    // Construct the directory name
    let dirName: string;
    if (location) {
      const fullName = `${service.name} (${location.name})`;
      dirName = SERVICE_DIR_MAP[fullName] || generateSlug(service.name, location.code);
    } else {
      dirName = service.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    }
    
    const [uptimeRes, responseTimeRes] = await Promise.all([
      fetch(`/api/${dirName}/uptime.json`),
      fetch(`/api/${dirName}/response-time.json`)
    ]);

    if (!uptimeRes.ok || !responseTimeRes.ok) {
      return {
        name: location ? `${service.name} (${location.name})` : service.name,
        url: service.url,
        statusUrl: service.statusUrl,
        status: 'unknown',
        uptime: 'N/A',
        responseTime: 0,
        lastChecked: new Date().toISOString(),
        error: `Unable to fetch data (HTTP ${uptimeRes.status || responseTimeRes.status})`,
        ...(location && { location })
      };
    }

    const uptimeData: UptimeData = await uptimeRes.json();
    const responseTimeData: ResponseTimeData = await responseTimeRes.json();

    // Determine status based on uptime percentage
    const uptimePercent = parseFloat(uptimeData.message.replace('%', ''));
    let status: 'up' | 'down' | 'degraded' = 'up';

    if (uptimePercent === 0) {
      status = 'down';
    } else if (uptimePercent < 99) {
      status = 'degraded';
    }

    // Extract response time (remove 'ms' and convert to number)
    const responseTimeMatch = responseTimeData.message.match(/(\d+)/);
    const responseTime = responseTimeMatch ? parseInt(responseTimeMatch[1]) : 0;

    return {
      name: location ? `${service.name} (${location.name})` : service.name,
      url: service.url,
      statusUrl: service.statusUrl,
      status,
      uptime: uptimeData.message,
      responseTime,
      lastChecked: new Date().toISOString(),
      ...(location && { location })
    };
  } catch (error) {
    console.error(`Error fetching status for ${serviceId}:`, error);
    return {
      name: location ? `${service.name} (${location.name})` : service.name,
      url: service.url,
      statusUrl: service.statusUrl,
      status: 'unknown',
      uptime: 'N/A',
      responseTime: 0,
      lastChecked: new Date().toISOString(),
      error: error instanceof Error ? error.message : 'Failed to fetch status data',
      ...(location && { location })
    };
  }
}

function generateSlug(serviceName: string, locationCode: string): string {
  const serviceSlug = serviceName.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  return `${serviceSlug}-${locationCode}`;
}

export async function getAllServicesStatus(): Promise<ServiceStatus[]> {
  const results: ServiceStatus[] = [];
  
  for (const service of SERVICES) {
    for (const location of LOCATIONS) {
      const status = await getServiceStatus(service.id, location.code);
      results.push(status);
    }
  }

  // Return all services, including those with errors
  return results;
}

export async function getServiceStatusByLocation(serviceId: string): Promise<Map<string, ServiceStatus>> {
  const statusMap = new Map<string, ServiceStatus>();
  
  for (const location of LOCATIONS) {
    const status = await getServiceStatus(serviceId, location.code);
    statusMap.set(location.code, status);
  }
  
  return statusMap;
}
