owner: hratchyan
repo: status
user-agent: hratchyan-status-monitor

sites:
# Major Platforms with Status APIs
- name: Zapier
  url: https://status.zapier.com/api/v2/status.json
  method: GET
  expectedStatusCodes: [200]

- name: Salesforce
  url: https://api.status.salesforce.com/v1/instances/status
  method: GET

- name: Google Cloud
  url: https://status.cloud.google.com/summary.json
  method: GET

- name: Microsoft Azure
  url: https://azure.status.microsoft.com/en-us/status/feed/
  method: GET

- name: CallRail
  url: https://status.callrail.com/api/v2/status.json
  method: GET

# WordPress Sites
- name: Main WordPress Site (hratchyan.com)
  url: https://hratchyan.com/wp-admin/admin-ajax.php?action=heartbeat
  method: POST
  expectedStatusCodes: [200]
  maxResponseTime: 10000

status-website:
  name: "Marketing Operations Status"
  cname: statuscheck.hratchyan.com
  baseUrl: /

  introTitle: "**Marketing Operations Status**"
  introMessage: "Real-time monitoring of marketing tools and services"

  theme: light
  navbar:
    - title: Status
      href: /
    - title: History
      href: /history

  # Custom branding
  logo: https://hratchyan.com/wp-content/uploads/2024/01/hratchyan-logo.png
  favicon: https://hratchyan.com/favicon.ico

  # Custom colors
  colors:
    primary: "#1a365d"  # Dark blue
    secondary: "#2d3748" # Gray
    success: "#38a169"  # Green
    warning: "#d69e2e"  # Yellow
    danger: "#e53e3e"   # Red
    info: "#3182ce"     # Blue

  # Custom template
  htmlTemplate: index.html

# Webhook notifications (for custom integrations)
notifications:
  - type: webhook
    url: https://your-webhook-endpoint.com/upptime-notification
    headers:
      Authorization: "Bearer YOUR_WEBHOOK_TOKEN"
      Content-Type: "application/json"
    body: |
      {
        "status": "{{ status }}",
        "site": "{{ site }}",
        "time": "{{ time }}",
        "url": "{{ url }}",
        "responseTime": "{{ responseTime }}",
        "timestamp": "{{ timestamp }}"
      }
